name: scalepluckernet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.11.0.dev20260214+cu128
      - torchvision==0.26.0.dev20260214+cu128
      - numpy
      - easydict
      - tensorboardx
      - msgpack
      - scikit-learn
      - tqdm
