#!/usr/bin/env python3
"""
train_slam_maps.py
==================
Fine-tune ScalePluckerNet on SLAM-map pairs generated by
scripts/generate_slam_map_dataset.py.

Key differences from train_cross_modal.py:
  - Dataset: slam_map_train / slam_map_valid  (200×200 lines, not 200×700)
  - Noise model: σ=0.5–3.0 m moment noise (real SLAM drift vs 0.02–0.20 m)
  - Scale range: 1.0–6.0 (mono vs RGB-D, not 0.1–10×)
  - Both sides are SLAM-density (200 lines), so normalize_n_lines=200 for both
  - Starts from the cross-modal checkpoint (already adapted to line-cloud pairs)

Run from the ScalePluckerNet/ directory:
  cd /home/rueyday/scale-aware-cross-modal-registration/ScalePluckerNet
  /home/rueyday/miniconda3/envs/depth_anything/bin/python train_slam_maps.py

Prepare data first:
  python scripts/generate_slam_map_dataset.py \\
      --db_train ../seq01_metric.db ../Structure-PLP-SLAM/replica_room0_map.db \\
                 ../Structure-PLP-SLAM/replica_room1_map.db \\
      --db_valid ../Structure-PLP-SLAM/replica_room1_mono_map_new.db \\
      --out_dir  dataset \\
      --dataset  slam_map \\
      --n_pairs_train 4000 \\
      --n_pairs_valid 600
"""

import os
import sys
import random
import logging
from datetime import date

import torch
import torch.optim as optim
import torch.backends.cudnn as cudnn
from torch.utils.data import DataLoader
from easydict import EasyDict as edict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(SCRIPT_DIR, "PlueckerNet"))
sys.path.insert(0, SCRIPT_DIR)

from config import get_config
from sim3.dataloader import Sim3PluckerData, LiveSim3PluckerData
from sim3.trainer import Sim3Trainer

logging.basicConfig(
    format="%(asctime)s %(message)s",
    datefmt="%m/%d %H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logging.getLogger().setLevel(logging.INFO)

# v15: held-out 7-Scenes val split (1 seq/scene), fine-tune from v14 best.
PRETRAINED = os.path.join(
    SCRIPT_DIR, "output", "slam_map", "2026-05-20-slam-maps-v14", "best_val_checkpoint.pth"
)

import glob as _glob

# DB paths for LiveSim3PluckerData
_SPN = SCRIPT_DIR
_SLAM = os.path.join(os.path.dirname(_SPN), "Structure-PLP-SLAM")
_ROOT = os.path.dirname(_SPN)

# One sequence per 7-Scenes scene held out for validation only — NOT in training
_7SCENES_VAL_HELD_OUT = {
    "7scenes_chess_seq06_map.db",
    "7scenes_fire_seq04_map.db",
    "7scenes_heads_seq02_map.db",
    "7scenes_office_seq10_map.db",
    "7scenes_pumpkin_seq06_map.db",
    "7scenes_redkitchen_seq12_map.db",
    "7scenes_stairs_seq06_map.db",
}

_STATIC_DBS = [
    f"{_SLAM}/replica_room0_map.db",
    f"{_SLAM}/replica_room1_map.db",
    f"{_SLAM}/replica_office0_gt_map.db",
    f"{_SLAM}/replica_office1_gt_map.db",
    f"{_SLAM}/replica_office2_gt_map.db",
    f"{_SLAM}/replica_office3_gt_map.db",
    f"{_SLAM}/replica_office4_gt_map.db",
    f"{_SLAM}/replica_room0_mono_slow.db",
    f"{_SLAM}/replica_room1_mono_map_new.db",
    f"{_SLAM}/kitti_00_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg3_long_office_household_run1_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg3_long_office_household_run2_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg3_long_office_household_run3_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg3_long_office_household_run4_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg3_long_office_household_run5_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg1_desk_run1_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg1_desk_run2_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg1_desk_run3_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg2_xyz_run1_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg2_xyz_run2_map.db",
    f"{_SLAM}/tum_rgbd_dataset_freiburg2_xyz_run3_map.db",
    f"{_SLAM}/tum_rgbd_rgbd_dataset_freiburg1_desk_run1_map.db",
    f"{_SLAM}/tum_rgbd_rgbd_dataset_freiburg1_desk_run2_map.db",
    f"{_SLAM}/tum_rgbd_rgbd_dataset_freiburg2_xyz_run1_map.db",
    f"{_SLAM}/tum_rgbd_rgbd_dataset_freiburg2_xyz_run2_map.db",
    f"{_SLAM}/tum_rgbd_rgbd_dataset_freiburg3_long_office_household_run1_map.db",
    f"{_SLAM}/seq02_map.db",
    f"{_SLAM}/seq02_map_midlines.db",
    f"{_ROOT}/seq01_metric_midlines.db",
]

# 7-Scenes training maps: all discovered, minus held-out val sequences
_7SCENES_DBS = [
    p for p in sorted(_glob.glob(f"{_SLAM}/7scenes_*_map.db"))
    if os.path.basename(p) not in _7SCENES_VAL_HELD_OUT
]

TRAIN_DB_PATHS = _STATIC_DBS + _7SCENES_DBS


def main():
    configs = get_config()

    # ── Dataset ───────────────────────────────────────────────────────────────
    # slam_map_train / slam_map_valid produced by generate_slam_map_dataset.py
    configs.dataset     = "slam_map"
    configs.data_dir    = os.path.join(SCRIPT_DIR, "dataset")
    configs.train_phase = "train"
    configs.val_phase   = "valid"

    # ── Model (same architecture as cross-modal run) ──────────────────────────
    configs.model        = "KNNContextNormNet"
    configs.net_depth    = 12
    configs.net_nchannel = 128
    configs.GNN_layers   = ["self", "cross"] * 6
    configs.net_gcnorm   = True
    configs.net_batchnorm = True
    configs.net_topK     = 2000
    configs.net_lambda   = 0.1
    configs.net_maxiter  = 30
    configs.net_knn      = 10
    configs.in_channel   = 6          # pure Plücker (6D), no LAB

    # Both sides are SLAM-density (200 lines each)
    configs.normalize_n_lines   = 200
    configs.normalize_n_inliers = 60   # ~30% of 200 (realistic for SLAM maps)
    configs.ransac_type = "sim3"
    configs.best_val_metric = "avg_inlier_ratio"  # decouple from RANSAC variance
    configs.pose_loss_weight = 0.0   # disabled: pose loss hurt v10 vs v8 (19.4% vs 20.4%)

    # ── Training ──────────────────────────────────────────────────────────────
    configs.out_dir     = os.path.join(SCRIPT_DIR, "output")
    configs.model_nb    = str(date.today()) + "-slam-maps-v15"
    configs.gpu_inds    = 0
    configs.use_gpu     = True

    configs.train_batch_size   = 16    # smaller — 200×200 pairs are lighter
    configs.train_lr           = 1e-5  # fine-tuning LR from v8
    configs.train_weight_decay = 1e-3
    configs.train_momentum     = 0.8
    configs.exp_gamma          = 1.0
    configs.train_epoches      = 300
    configs.train_start_epoch  = 0
    configs.train_save_freq_epoch = 1
    configs.val_epoch_freq     = 1
    configs.val_max_iter       = -1
    configs.iter_size          = 1
    configs.optimizer          = "Adam"
    configs.train_num_thread   = 4
    configs.val_num_thread     = 1
    configs.train_seed         = 42
    configs.print_freq         = 20

    # ── Load cross-modal checkpoint as starting weights ───────────────────────
    if os.path.isfile(PRETRAINED):
        logging.info(f"Fine-tuning from: {PRETRAINED}")
        configs.weights = PRETRAINED
    else:
        logging.warning(f"Checkpoint not found: {PRETRAINED}")
        logging.warning("Training from scratch — set PRETRAINED to a valid path")
        configs.weights = ""
    configs.resume     = None
    configs.resume_dir = None

    dconfig = vars(configs)
    logging.info("===> SLAM-map training config v15 (held-out 7-Scenes val, fine-tune from v14)")
    for k, v in sorted(dconfig.items()):
        logging.info("    {:30s}: {}".format(k, v))
    configs = edict(dconfig)

    if configs.train_seed is not None:
        random.seed(configs.train_seed)
        torch.manual_seed(configs.train_seed)
        torch.cuda.manual_seed(configs.train_seed)
        cudnn.deterministic = True

    train_loader = DataLoader(
        LiveSim3PluckerData(
            db_paths=TRAIN_DB_PATHS,
            epoch_size=16000,
            config=configs,
            inter_map_ratio=0.3,
        ),
        batch_size=configs.train_batch_size,
        shuffle=True,
        drop_last=True,
        num_workers=configs.train_num_thread,
    )
    val_loader = DataLoader(
        Sim3PluckerData(phase="valid", config=configs),
        batch_size=1,
        shuffle=False,
        drop_last=False,
        num_workers=configs.val_num_thread,
    )

    trainer = Sim3Trainer(configs, train_loader, val_loader)

    # Load pretrained weights (fine-tune only — don't resume optimizer state)
    if configs.weights:
        state = torch.load(configs.weights, weights_only=False,
                           map_location=trainer.device)
        sd = state.get("state_dict", state)
        missing, unexpected = trainer.model.load_state_dict(sd, strict=False)
        if missing:
            logging.info(f"  Missing keys  ({len(missing)}): {missing[:5]}")
        if unexpected:
            logging.info(f"  Unexpected keys ({len(unexpected)}): {unexpected[:5]}")
        logging.info("  Pretrained weights loaded successfully.")

    # CosineAnnealingLR — avoids post-peak degradation seen with ExponentialLR
    trainer.scheduler = optim.lr_scheduler.CosineAnnealingLR(
        trainer.optimizer,
        T_max=100,   # anneal from 1e-5 → 1e-7 over 100 epochs, then repeat
        eta_min=1e-7,
    )

    trainer.train()


if __name__ == "__main__":
    main()
